import os

TOKEN = os.getenv("TOKEN")

OWNER_ID = 123456789012345678  # <-- REPLACE WITH YOUR USER ID

DEFAULT_PREFIX = "!"

LAVALINK_HOST = os.getenv("LAVALINK_HOST")
LAVALINK_PORT = int(os.getenv("LAVALINK_PORT", 25574))
LAVALINK_PASSWORD = os.getenv("LAVALINK_PASSWORD")
